from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import csv
import os
from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
import requests  # Import the requests library
from selenium.webdriver.chrome.options import Options
import chromedriver_binary # adds the chromedriver binary to the path

# Configure ChromeOptions for the regular browser instance
options = webdriver.ChromeOptions()
options.add_argument("start-maximized")
options.add_argument('--disable-blink-features=AutomationControlled')
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)

# Initialize Chrome WebDriver with options
driver = webdriver.Chrome(options=options)


# # Initialize the Chrome driver
# driver = webdriver.Chrome()

# # Initialize Chrome WebDriver in headless mode
# chrome_options = Options()
# chrome_options.add_argument("--headless")
# headless_driver = webdriver.Chrome(options=chrome_options)


# Create a list of example URLs
urls = [
    "https://www.apartments.com/106-hyde-park-ave-boston-ma/jtz4jy7/",
    "https://www.apartments.com/1-blackstone-st-cambridge-ma-unit-1b/p9rpc5t/",
    "https://www.apartments.com/1-briarfield-rd-milton-ma-unit-a/3fpg6pg/",
    "https://www.apartments.com/1-devonshire-st-boston-ma/1xps3w4/",
    "https://www.apartments.com/1-fayette-st-cambridge-ma-unit-2/nez13zp/",
    "https://www.apartments.com/1-johnny-ct-boston-ma-unit-1/wny464h/",
    "https://www.apartments.com/10-bearse-ave-boston-ma-unit-3/db3zsvh/",
    "https://www.apartments.com/10-bennington-st-newton-ma-unit-1/vcpqzfe/",
    "https://www.apartments.com/10-charlesgate-e-boston-ma-unit-201/d384s4k/",
    "https://www.apartments.com/10-clipper-ship-ln-boston-ma/vyy93sg/",
    "https://www.apartments.com/10-cufflin-st-boston-ma-unit-2/1vzfy64/",
    "https://www.apartments.com/10-cufflin-st-boston-ma/fmyyb3v/",
    "https://www.apartments.com/10-glenmont-rd-boston-ma-unit-2/1t09mp7/",
    "https://www.apartments.com/10-oliva-rd-boston-ma-unit-2/jnj6646/",
    "https://www.apartments.com/10-pratt-st-boston-ma-unit-2/mbvkh1j/",
    "https://www.apartments.com/10-saco-st-boston-ma-unit-4/3feqbtd/",
    "https://www.apartments.com/10-wave-ave-boston-ma/1perkf5/",
    "https://www.apartments.com/10-westland-ave-boston-ma-unit-u-40/mx8zqdk/",
    "https://www.apartments.com/10-winter-st-cambridge-ma-unit-1/gdnx4hw/",
    "https://www.apartments.com/100-1st-ave-boston-ma/x059wln/",
    "https://www.apartments.com/100-pearl-st-chelsea-ma-unit-13/c4wvx1d/",
    "https://www.apartments.com/101-broad-st-boston-ma-unit-6b/smvv8c4/",
    "https://www.apartments.com/101-chelsea-st-boston-ma/cjrgl8f/",
    "https://www.apartments.com/1028-commonwealth-ave-boston-ma/14w0f64/",
    "https://www.apartments.com/1029-tremont-st-boston-ma-unit-3/r187251/",
    "https://www.apartments.com/105-brookline-st-chestnut-hill-ma-unit-314/yqtrgtt/",
    "https://www.apartments.com/105-forest-hills-st-boston-ma/4l4qngj/",
    "https://www.apartments.com/106-forest-hills-st-boston-ma-unit-103/cb1mq9g/",
    "https://www.apartments.com/106-forest-hills-st-boston-ma-unit-3/1x3c636/",
    "https://www.apartments.com/106-forest-hills-st-boston-ma/07mljd2/",
    "https://www.apartments.com/106-forest-hills-st-boston-ma/z82409y/",
    "https://www.apartments.com/106-myrtle-st-boston-ma/pgeh4qr/",
    "https://www.apartments.com/107-buttonwood-st-boston-ma-unit-3/rwdwvm3/",
    "https://www.apartments.com/107-chandler-st-boston-ma-unit-g/w7qm4el/",
    "https://www.apartments.com/108-appleton-st-boston-ma-unit-a/hf3tb02/",
    "https://www.apartments.com/108-buttonwood-st-boston-ma-unit-3/3k25e6d/",
    "https://www.apartments.com/108-buttonwood-st-boston-ma-unit-3/fwbdw8r/",
    "https://www.apartments.com/11-breck-ave-boston-ma-unit-2aa/2blzw58/",
    "https://www.apartments.com/11-crest-hill-rd-somerville-ma-unit-2/zcgf56z/",
    "https://www.apartments.com/11-holly-ave-cambridge-ma-unit-2/c233lse/",
    "https://www.apartments.com/11-joseph-st-boston-ma-unit-1/5vvx2xq/",
    "https://www.apartments.com/11-new-st-boston-ma-unit-22/8qrw131/",
    "https://www.apartments.com/11-new-st-boston-ma/f7nnzwv/",
    "https://www.apartments.com/11-peterborough-st-boston-ma-unit-1/1ve1nt7/",
    "https://www.apartments.com/11-sparhawk-st-boston-ma-unit-1/2xfm6s9/",
    "https://www.apartments.com/11-stickney-ave-somerville-ma-unit-1/00gh4n1/",
    "https://www.apartments.com/1110-massachusetts-ave-cambridge-ma-unit-4/91fefb5/",
    "https://www.apartments.com/1148-washington-st-boston-ma/31mpmkd/",
    "https://www.apartments.com/115-kilsyth-rd-boston-ma-unit-1/hffgsr0/",
    "https://www.apartments.com/115-union-st-boston-ma-unit-3/ey3kkln/",
    "https://www.apartments.com/116-gladstone-st-boston-ma-unit-2/nyyb4wq/",
    "https://www.apartments.com/116-riverway-boston-ma-unit-16/ffdk0xr/",
    "https://www.apartments.com/116-willow-st-cambridge-ma-unit-4/w2c3bzj/",
    "https://www.apartments.com/1165-commonwealth-ave-boston-ma/1yw8jv5/",
    "https://www.apartments.com/117-harrishof-st-boston-ma-unit-2/j06wq96/",
    "https://www.apartments.com/118-governor-winthrop-rd-somerville-ma-unit-1/r2nvd82/",
    "https://www.apartments.com/118-lake-st-boston-ma/vt8lfjf/",
    "https://www.apartments.com/119-george-st-boston-ma-unit-2/vnp16yf/",
    "https://www.apartments.com/12-eulita-ter-boston-ma-unit-2/ecsth3p/",
    "https://www.apartments.com/12-lopez-ave-cambridge-ma-unit-2/130cns5/",
    "https://www.apartments.com/12-lopez-ave-cambridge-ma-unit-2/97x3fr6/",
    "https://www.apartments.com/12-pratt-st-boston-ma-unit-1/vts783g/",
    "https://www.apartments.com/12-wensley-st-boston-ma-unit-3n/gtrmmzw/",
    "https://www.apartments.com/12-winter-st-boston-ma/r3lh363/",
    "https://www.apartments.com/120-gladstone-st-boston-ma-unit-2/zx0x93x/",
    "https://www.apartments.com/121-bigelow-st-boston-ma-unit-2/njenrbm/",
    "https://www.apartments.com/122-bennett-st-boston-ma-unit-1a/clbbsrg/",
    "https://www.apartments.com/122-cottage-st-boston-ma-unit-4f/eemqqwp/",
    "https://www.apartments.com/123-border-st-boston-ma-unit-5/hqxf731/",
    "https://www.apartments.com/123-boston-st-boston-ma-unit-1/mxp6pbk/",
    "https://www.apartments.com/123-boston-st-boston-ma-unit-2/mt7ez4k/",
    "https://www.apartments.com/123-sewall-ave-brookline-ma-unit-1a/nsqls8m/",
    "https://www.apartments.com/123-sutherland-rd-boston-ma-unit-g/3rj443d/",
    "https://www.apartments.com/123-trenton-st-boston-ma-unit-3/94kyqx6/",
    "https://www.apartments.com/124-kenrick-st-boston-ma-unit-3/nb7r8ym/",
    "https://www.apartments.com/126a-babcock-st-brookline-ma-unit-26/n4rj5dp/",
    "https://www.apartments.com/127-blue-hill-ave-milton-ma-unit-1/0msq4k0/",
    "https://www.apartments.com/127-eliot-st-chestnut-hill-ma-unit-1/dc4k8hk/",
    "https://www.apartments.com/127-nonantum-st-boston-ma-unit-2/fdfp9wv/",
    "https://www.apartments.com/128-everett-st-boston-ma-unit-2/2zknzpb/",
    "https://www.apartments.com/129-sutherland-rd-boston-ma/7k2glwx/",
    "https://www.apartments.com/1298-commonwealth-ave-boston-ma-unit-6/3s0nvmd/",
    "https://www.apartments.com/13-glenley-ter-boston-ma-unit-2/xltwrcn/",
    "https://www.apartments.com/13-pleasant-st-cambridge-ma-unit-1/zfswvlz/",
    "https://www.apartments.com/13-pleasant-st-cambridge-ma-unit-2/8x2mjd3/",
    "https://www.apartments.com/13-sachem-st-boston-ma-unit-1/0mg5w21/",
    "https://www.apartments.com/13-sparhawk-st-boston-ma/jjzz7k4/",
    "https://www.apartments.com/13-sparhawk-st-boston-ma/z8lnd0z/",
    "https://www.apartments.com/1306-columbia-rd-boston-ma-unit-3e/4zqqmtk/",
    "https://www.apartments.com/132-lake-shore-rd-boston-ma-unit-1/x2wp1bn/",
    "https://www.apartments.com/1340-boylston-st-boston-ma-unit-1a/ps8pm3t/",
    "https://www.apartments.com/136-parsons-st-boston-ma/4krls0l/",
    "https://www.apartments.com/137-fayerweather-st-cambridge-ma-unit-1/1w8cel6/",
    "https://www.apartments.com/139-fresh-pond-pkwy-cambridge-ma/srwd9m4/",
    "https://www.apartments.com/14-batchelder-st-boston-ma-unit-2/3ffc59g/",
    "https://www.apartments.com/14-bothwell-rd-boston-ma-unit-1/zwsk5gy/",
    "https://www.apartments.com/14-glenmont-rd-boston-ma-unit-1/mybv8gj/",
    "https://www.apartments.com/14-linnaean-st-cambridge-ma/q9htg4x/",
    "https://www.apartments.com/14-marion-st-brookline-ma/h7kbng1/",
    "https://www.apartments.com/14-parmenter-st-boston-ma-unit-403/y92emwr/",
    "https://www.apartments.com/14-portsmouth-st-boston-ma-unit-c/4rszhcj/",
    "https://www.apartments.com/14-townsend-st-boston-ma-unit-4/c1g6m2f/",
    "https://www.apartments.com/14-townsend-st-boston-ma-unit-4/y6660qv/",
    "https://www.apartments.com/14-w-broadway-boston-ma-unit-201half-fee/c4vwzje/",
    "https://www.apartments.com/140-kenrick-st-boston-ma-unit-2/zgyc5zx/",
    "https://www.apartments.com/141-chelsea-st-boston-ma-unit-3/vpt14tg/",
    "https://www.apartments.com/1410-columbia-rd-boston-ma/z14qn0w/",
    "https://www.apartments.com/1416-commonwealth-ave-boston-ma-unit-402/zgz40gy/",
    "https://www.apartments.com/1424-columbia-rd-boston-ma/gykk8cw/",
    "https://www.apartments.com/1426-columbia-rd-boston-ma/l2gz1tf/",
    "https://www.apartments.com/1430-tremont-st-boston-ma-unit-b4n/czsv8se/",
    "https://www.apartments.com/1463-beacon-st-brookline-ma-unit-4/sflb7d5/",
    "https://www.apartments.com/148-allston-st-cambridge-ma-unit-1/gzr22vz/",
    "https://www.apartments.com/149-g-st-boston-ma/3981dzg/",
    "https://www.apartments.com/15-germania-st-boston-ma-unit-3/1m2vd77/",
    "https://www.apartments.com/15-greycliff-rd-boston-ma-unit-2/0f4gjz2/",
    "https://www.apartments.com/15-kelley-ct-boston-ma-unit-02n/qz9e5ry/",
    "https://www.apartments.com/15-romsey-st-boston-ma-unit-3/jnhlcq4/",
    "https://www.apartments.com/15-sparhawk-st-boston-ma-unit-1/cl9lp8g/",
    "https://www.apartments.com/15-sparhawk-st-boston-ma/k2wpb59/",
    "https://www.apartments.com/15-ward-st-boston-ma-unit-4/7mq28sz/",
    "https://www.apartments.com/15-westland-ave-boston-ma-unit-39/z1wspty/",
    "https://www.apartments.com/150-south-st-boston-ma-unit-3/qr0h0ey/",
    "https://www.apartments.com/151-g-st-boston-ma/nr7sl8q/",
    "https://www.apartments.com/151-park-dr-boston-ma/vjfs8ye/",
    "https://www.apartments.com/1522-vfw-pky-boston-ma-unit-202/5bpk59p/",
    "https://www.apartments.com/1525-cambridge-st-cambridge-ma-unit-2/rrd7lk0/",
    "https://www.apartments.com/153-cherry-st-cambridge-ma-unit-1/xvfbk1p/",
    "https://www.apartments.com/153-foster-st-boston-ma-unit-3/hvnd352/",
    "https://www.apartments.com/154-bigelow-st-boston-ma/wv3xzsj/",
    "https://www.apartments.com/155-strathmore-rd-boston-ma/e78jxrm/",
    "https://www.apartments.com/157-bowdoin-st-boston-ma-unit-1/vpc3w1f/",
    "https://www.apartments.com/158-boston-st-boston-ma-unit-3/d3tmr0l/",
    "https://www.apartments.com/1583-beacon-st-brookline-ma-unit-3/qrsw5lw/",
    "https://www.apartments.com/16-crescent-circuit-s-cres-boston-ma-unit-2/cp8r1wf/",
    "https://www.apartments.com/16-donnybrook-rd-boston-ma-unit-2/58e8b2n/",
    "https://www.apartments.com/16-elko-st-boston-ma-unit-1/l0d5l7g/",
    "https://www.apartments.com/16-garrison-rd-brookline-ma-unit-7/0qg74v3/",
    "https://www.apartments.com/16-irving-st-boston-ma-unit-8/f5403jt/",
    "https://www.apartments.com/16-oakview-ter-boston-ma-unit-3/swp2mg4/",
    "https://www.apartments.com/16-parmenter-st-boston-ma-unit-403/wrtxq6k/",
    "https://www.apartments.com/16-s-crescent-circuit-boston-ma-unit-2/3lke18d/",
    "https://www.apartments.com/160-bigelow-st-boston-ma/52h7qsm/",
    "https://www.apartments.com/160-e-berkeley-st-boston-ma-unit-305/jmq2g47/",
    "https://www.apartments.com/160-e-berkeley-st-boston-ma/879z0l3/",
    "https://www.apartments.com/162-lincoln-st-boston-ma-unit-1610/jjwd5v4/",
    "https://www.apartments.com/162-wachusett-st-jamaica-plain-ma-unit-1/s91dzx7/",
    "https://www.apartments.com/164-bigelow-st-boston-ma-unit-1/qm6cm6w/",
    "https://www.apartments.com/1661-washington-st-boston-ma/y6hn2er/",
    "https://www.apartments.com/167-thorndike-st-cambridge-ma-unit-1/hmzkrn0/",
    "https://www.apartments.com/168-bigelow-st-boston-ma/4t5m91h/",
    "https://www.apartments.com/169-monsignor-obrien-hwy-cambridge-ma-unit-601/tttlrsc/",
    "https://www.apartments.com/169-thorndike-st-cambridge-ma-unit-2/kwdlkd8/",
    "https://www.apartments.com/169-tremont-st-newton-ma-unit-1/w6pcwel/",
    "https://www.apartments.com/17-falkland-st-boston-ma-unit-2/39hltxd/",
    "https://www.apartments.com/17-grove-st-boston-ma-unit-4/0bhb923/",
    "https://www.apartments.com/17-middle-st-boston-ma-unit-3/jvecb85/",
    "https://www.apartments.com/17-nottinghill-rd-boston-ma-unit-1/bx4mzy8/",
    "https://www.apartments.com/17-nottinghill-rd-boston-ma-unit-2n/rn8df02/",
    "https://www.apartments.com/17-winter-st-boston-ma/8mz1zg1/",
    "https://www.apartments.com/171-173-i-st-boston-ma-unit-2/khyq6f9/",
    "https://www.apartments.com/171-cambridge-st-boston-ma-unit-2/0l9men3/",
    "https://www.apartments.com/171-south-st-boston-ma-unit-5a/4qf333h/",
    "https://www.apartments.com/171-thorndike-st-cambridge-ma-unit-1/tzqbx68/",
    "https://www.apartments.com/1719-commonwealth-ave-boston-ma-unit-3/w7y9f4l/",
    "https://www.apartments.com/172-green-st-boston-ma/6fs4rhv/",
    "https://www.apartments.com/173-border-st-boston-ma/hcvzzr0/",
    "https://www.apartments.com/175-high-st-brookline-ma-unit-1/rkd6qg0/",
    "https://www.apartments.com/177-bennington-st-boston-ma-unit-4/hm6bc43/",
    "https://www.apartments.com/1789-commonwealth-ave-boston-ma-unit-1/25sd3nb/",
    "https://www.apartments.com/1789-commonwealth-ave-boston-ma-unit-1/clxcwdd/",
    "https://www.apartments.com/1789-commonwealth-ave-boston-ma/0wvyxw2/",
    "https://www.apartments.com/1789-commonwealth-ave-boston-ma/v7fe52e/",
    "https://www.apartments.com/1789-commonwealth-avenue-boston-ma/1xmbc74/",
    "https://www.apartments.com/18-bradbury-st-boston-ma-unit-1/hkj7cd0/",
    "https://www.apartments.com/18-gibson-st-boston-ma-unit-2/djd12eh/",
    "https://www.apartments.com/18-glenmont-rd-boston-ma-unit-1/3bvpm7d/",
    "https://www.apartments.com/18-glenville-ave-boston-ma-unit-1/c98l68e/",
    "https://www.apartments.com/18-grove-boston-ma/zctnw8w/",
    "https://www.apartments.com/18-grove-st-boston-ma-unit-1/jj4mkh5/",
    "https://www.apartments.com/18-highgate-st-boston-ma/ybn0r9s/",
    "https://www.apartments.com/18-holton-st-boston-ma/vk32zeg/",
    "https://www.apartments.com/18-hunnewell-ave-boston-ma-unit-2/2szbh9c/",
    "https://www.apartments.com/18-lopez-st-cambridge-ma-unit-3/c915jtf/",
    "https://www.apartments.com/18-parmenter-st-boston-ma-unit-3/9mkpvv5/",
    "https://www.apartments.com/18-parmenter-st-boston-ma-unit-403/q5bmqfz/",
    "https://www.apartments.com/18-parmenter-st-boston-ma-unit-403/r25n972/",
    "https://www.apartments.com/18-parmenter-st-boston-ma-unit-403/vm7znze/",
    "https://www.apartments.com/181-harvard-st-brookline-ma-unit-3a/ce15b9d/",
    "https://www.apartments.com/181-harvard-st-brookline-ma/cbq8m9g/",
    "https://www.apartments.com/181-m-st-boston-ma-unit-2/nemkclp/",
    "https://www.apartments.com/185-green-st-boston-ma-unit-3/jd9q5v5/",
    "https://www.apartments.com/1860-commonwealth-ave-boston-ma-unit-3/t77c9d8/",
    "https://www.apartments.com/187-harvard-st-brookline-ma-unit-3/jvvpq24/",
    "https://www.apartments.com/189-chestnut-hill-ave-boston-ma-unit-19/wrfp0dh/",
    "https://www.apartments.com/19-archdale-rd-boston-ma-unit-1/383f65f/",
    "https://www.apartments.com/19-dorset-st-boston-ma-unit-3/g48cg1z/",
    "https://www.apartments.com/19-edward-t-sullivan-rd-cambridge-ma-unit-3/9ffc2z7/",
    "https://www.apartments.com/19-fairbanks-st-brookline-ma-unit-3/rpjdc33/",
    "https://www.apartments.com/19-litchfield-st-boston-ma-unit-2/nv12ljp/",
    "https://www.apartments.com/19-nottinghill-rd-boston-ma-unit-nm/yhdffgr/",
    "https://www.apartments.com/19-parker-hill-ave-boston-ma-unit-2/jwffm87/",
    "https://www.apartments.com/19-saint-lukes-rd-boston-ma-unit-1/q0ce0by/",
    "https://www.apartments.com/19-worthington-st-boston-ma-unit-2/gnk4hgy/",
    "https://www.apartments.com/190-green-st-boston-ma/wzw2n1k/",
    "https://www.apartments.com/191-bunker-hill-st-boston-ma-unit-apt-306/f32p8jv/",
    "https://www.apartments.com/191-porter-st-boston-ma-unit-5/n2rwh2q/",
    "https://www.apartments.com/194-emerson-st-boston-ma-unit-3/c2nhzvf/",
    "https://www.apartments.com/196-tremont-st-newton-ma-unit-3/et29r7n/",
    "https://www.apartments.com/198-brookline-ave-boston-ma/21crb7c/",
    "https://www.apartments.com/2-bow-st-cambridge-ma-unit-2/g971pgx/",
    "https://www.apartments.com/2-rossmore-rd-boston-ma-unit-2/t97qkm8/",
    "https://www.apartments.com/2-rossmore-rd-boston-ma/qt7e5gy/",
    "https://www.apartments.com/2-thane-st-boston-ma-unit-2/2614bgb/",
    "https://www.apartments.com/2-wellington-st-boston-ma-unit-6/knfdde8/",
    "https://www.apartments.com/20-brooks-st-boston-ma-unit-1/bd6yn5c/",
    "https://www.apartments.com/20-dawes-st-boston-ma/91fk6b7/",
    "https://www.apartments.com/20-howell-st-boston-ma-unit-2/6h87zhs/",
    "https://www.apartments.com/20-penniman-rd-boston-ma-unit-208/tvzsmk8/",
    "https://www.apartments.com/20-south-st-boston-ma/nqtd99q/",
    "https://www.apartments.com/20-westgate-rd-boston-ma-unit-1/071dz70/",
    "https://www.apartments.com/20-westland-ave-boston-ma-unit-39/j3w2z76/",
    "https://www.apartments.com/200-commonwealth-ave-chestnut-hill-ma-unit-1n/v9ctxxf/",
    "https://www.apartments.com/201-longwood-ave-brookline-ma/06vyb20/",
    "https://www.apartments.com/202-stuart-st-boston-ma/8mgc212/",
    "https://www.apartments.com/204-cambridge-st-boston-ma/xe3wc2m/",
    "https://www.apartments.com/207-aspinwall-ave-brookline-ma/gnr40cz/",
    "https://www.apartments.com/209-green-st-boston-ma-unit-206/43frfdl/",
    "https://www.apartments.com/21-nottinghill-rd-boston-ma/xk67n8p/",
    "https://www.apartments.com/21-sparhawk-st-boston-ma-unit-2/kyb0dmb/",
    "https://www.apartments.com/21-weitz-st-boston-ma-unit-2/rsd1xq1/",
    "https://www.apartments.com/211-green-st-boston-ma-unit-212/c21rm5g/",
    "https://www.apartments.com/211-green-st-boston-ma-unit-505/rdrcqv3/",
    "https://www.apartments.com/211-green-st-jamaica-plain-ma/rkj3l20/",
    "https://www.apartments.com/212-hemenway-st-boston-ma-unit-4/cvlklge/",
    "https://www.apartments.com/215-saint-paul-st-brookline-ma-unit-3/31j7w2f/",
    "https://www.apartments.com/216-newbury-st-boston-ma-unit-4/z53045w/",
    "https://www.apartments.com/217-south-st-boston-ma-unit-7/9qs9vb5/",
    "https://www.apartments.com/217-w-2nd-st-boston-ma/mlet6zh/",
    "https://www.apartments.com/219-w-2nd-st-boston-ma-unit-221/02zp5w2/",
    "https://www.apartments.com/22-concord-ave-somerville-ma-unit-2b/9dwfgv5/",
    "https://www.apartments.com/22-hayden-st-boston-ma/9bzhk47/",
    "https://www.apartments.com/22-laurel-st-watertown-ma-unit-2/e7fr02p/",
    "https://www.apartments.com/22-winslow-rd-brookline-ma-unit-1/evk057p/",
    "https://www.apartments.com/22-woodworth-st-boston-ma/r2995h2/",
    "https://www.apartments.com/220-old-colony-ave-boston-ma/ref1vm2/",
    "https://www.apartments.com/220-tremont-st-newton-ma-unit-1/ffjvxyv/",
    "https://www.apartments.com/221-w-2nd-st-boston-ma-unit-2/7fkcv2x/",
    "https://www.apartments.com/221-w-2nd-st-boston-ma/l8wd1lg/",
    "https://www.apartments.com/221-w-2nd-st-boston-ma/n61lxzp/",
    "https://www.apartments.com/23-elmore-st-boston-ma-unit-3/574qlvn/",
    "https://www.apartments.com/23-lambert-st-cambridge-ma-unit-2/73d7f6z/",
    "https://www.apartments.com/23-marcella-st-boston-ma-unit-2/4wplskh/",
    "https://www.apartments.com/23-morrow-rd-boston-ma-unit-2/xn8p42q/",
    "https://www.apartments.com/23-ward-st-boston-ma-unit-2/c143cce/",
    "https://www.apartments.com/230-brookline-st-cambridge-ma-unit-1/cv55bhg/",
    "https://www.apartments.com/230-everett-st-boston-ma-unit-8/5zr71yn/",
    "https://www.apartments.com/230-everett-st-boston-ma-unit-8/nzwmx1n/",
    "https://www.apartments.com/233-boylston-st-brookline-ma-unit-3/l2wvl7d/",
    "https://www.apartments.com/238-hemenway-st-boston-ma-unit-3/hsb03n0/",
    "https://www.apartments.com/24-annafran-st-boston-ma-unit-3/gv9k0zy/",
    "https://www.apartments.com/24-bentley-st-boston-ma-unit-1/qt1qc3x/",
    "https://www.apartments.com/24-breed-st-boston-ma-unit-1/yhq64xr/",
    "https://www.apartments.com/24-tower-st-boston-ma-unit-2/11mssn5/",
    "https://www.apartments.com/240-hanover-st-boston-ma-unit-510/716et2z/",
    "https://www.apartments.com/241-tremont-st-newton-ma-unit-1/bembx68/",
    "https://www.apartments.com/247-d-st-boston-ma/53gtntm/",
    "https://www.apartments.com/25-bennett-st-boston-ma/t4yqk3c/",
    "https://www.apartments.com/25-dwight-st-boston-ma-unit-4/x5nc3cp/",
    "https://www.apartments.com/25-g-st-boston-ma/9jb5hb7/",
    "https://www.apartments.com/25-greycliff-rd-boston-ma-unit-1/g28n1sw/",
    "https://www.apartments.com/25-henshaw-st-boston-ma-unit-2/dlwwjxk/",
    "https://www.apartments.com/25-lothrop-st-boston-ma-unit-2/jrr59m7/",
    "https://www.apartments.com/25-worthington-st-boston-ma-unit-1/yfnb0cs/",
    "https://www.apartments.com/250-newbury-st-boston-ma/29yy359/",
    "https://www.apartments.com/251-cambridge-st-boston-ma-unit-3/23h82x9/",
    "https://www.apartments.com/251-cambridge-st-boston-ma-unit-3/272m88b/",
    "https://www.apartments.com/251-cambridge-st-boston-ma-unit-3/28tbwkc/",
    "https://www.apartments.com/251-cambridge-st-boston-ma-unit-3/hqv4be0/",
    "https://www.apartments.com/251-cambridge-st-boston-ma-unit-3/kr0kc6c/",
    "https://www.apartments.com/255-somerville-ave-somerville-ma-unit-3/dln7bzh/",
    "https://www.apartments.com/258-chestnut-hill-ave-boston-ma/m8mkkwh/",
    "https://www.apartments.com/259-billings-st-quincy-ma/g9m21cz/",
    "https://www.apartments.com/259-marlborough-st-boston-ma-unit-11/pejjnrr/",
    "https://www.apartments.com/259-mount-auburn-st-cambridge-ma/gkbxx6x/",
    "https://www.apartments.com/26-boston-st-boston-ma-unit-2/xyqq36p/",
    "https://www.apartments.com/26-bothwell-rd-boston-ma/9mpyef5/",
    "https://www.apartments.com/26-nottinghill-rd-boston-ma-unit-2/xw130hm/",
    "https://www.apartments.com/26-pembroke-st-chelsea-ma-unit-1/7m08yfz/",
    "https://www.apartments.com/26-romsey-st-boston-ma-unit-1/94rksl5/",
    "https://www.apartments.com/265-park-st-boston-ma-unit-1/nxfcxtq/",
    "https://www.apartments.com/266-e-berkeley-st-boston-ma/8cfb862/",
    "https://www.apartments.com/266-gold-st-boston-ma-unit-1/3b2l9rf/",
    "https://www.apartments.com/27-buttonwood-st-boston-ma/qphzqhy/",
    "https://www.apartments.com/27-hereford-st-boston-ma/c0dsp3g/",
    "https://www.apartments.com/27-kelley-ct-boston-ma-unit-a/xcfc5kn/",
    "https://www.apartments.com/270-athens-st-boston-ma-unit-3/b79g7d8/",
    "https://www.apartments.com/270-athens-st-boston-ma-unit-ph/djlh0pl/",
    "https://www.apartments.com/277-lamartine-st-boston-ma/k5drebc/",
    "https://www.apartments.com/279-huron-ave-cambridge-ma-unit-6/zysr37x/",
    "https://www.apartments.com/279-lamartine-st-boston-ma-unit-2/1bbm7n4/",
    "https://www.apartments.com/28-brooks-st-boston-ma-unit-2/6ldeqmt/",
    "https://www.apartments.com/28-chatham-st-cambridge-ma-unit-2/qrhwfhz/",
    "https://www.apartments.com/28-claymoss-rd-boston-ma-unit-1/v8zk4jf/",
    "https://www.apartments.com/28-crosby-rd-newton-ma-unit-nm/h3ncsq1/",
    "https://www.apartments.com/28-manet-rd-newton-ma/6xq41wr/",
    "https://www.apartments.com/28-pennsylvania-ave-somerville-ma-unit-2/ppepkxv/",
    "https://www.apartments.com/2837-washington-st-boston-ma-unit-1/xemr5jn/",
    "https://www.apartments.com/287-kent-st-brookline-ma/t5lv8t8/",
    "https://www.apartments.com/29-concord-ave-cambridge-ma-unit-604/8kz1d92/",
    "https://www.apartments.com/29-falcon-st-boston-ma-unit-1/sdzqph6/",
    "https://www.apartments.com/29-msgr-patrick-j-lydon-way-boston-ma-unit-2/dfhcm3j/",
    "https://www.apartments.com/29-spring-garden-st-boston-ma-unit-1/w8rh4yk/",
    "https://www.apartments.com/299-dudley-st-boston-ma-unit-4/0dwb8z2/",
    "https://www.apartments.com/299-lexington-st-boston-ma-unit-3/1dnj4q4/",
    "https://www.apartments.com/299-lexington-st-boston-ma-unit-3/cd9p3hd/",
    "https://www.apartments.com/3-beckler-ave-boston-ma-unit-2/6847ldr/",
    "https://www.apartments.com/3-boylston-pl-boston-ma/x6nbbtn/",
    "https://www.apartments.com/3-guernsey-st-boston-ma-unit-3/cxx27jg/",
    "https://www.apartments.com/3-louisburg-sq-boston-ma-unit-ph/6101rjs/",
    "https://www.apartments.com/30-bothwell-rd-boston-ma/e7ttf5m/",
    "https://www.apartments.com/30-brackett-st-boston-ma-unit-3/zsblnmx/",
    "https://www.apartments.com/30-crosby-rd-newton-ma-unit-2/wnd7z2l/",
    "https://www.apartments.com/30-medfield-st-boston-ma-unit-5/kd6l2x8/",
    "https://www.apartments.com/303-d-st-boston-ma/7nyrvlw/",
    "https://www.apartments.com/303-dudley-st-boston-ma-unit-4/n0wqy6q/",
    "https://www.apartments.com/303-maverick-st-boston-ma-unit-3/ctwr98f/",
    "https://www.apartments.com/304-north-st-boston-ma/yyyybgs/",
    "https://www.apartments.com/305-chelsea-st-boston-ma-unit-3/816d1z2/",
    "https://www.apartments.com/307-elm-st-cambridge-ma-unit-2/c6hxp4e/",
    "https://www.apartments.com/31-6th-st-cambridge-ma/g62cx8w/",
    "https://www.apartments.com/31-auburn-st-brookline-ma/mlj4lnk/",
    "https://www.apartments.com/31-sacramento-st-cambridge-ma-unit-2/3ef03sd/",
    "https://www.apartments.com/31-sacramento-st-cambridge-ma-unit-2/60g2xlv/",
    "https://www.apartments.com/31-saint-lukes-rd-boston-ma/sn33ek4/",
    "https://www.apartments.com/31-worthington-st-boston-ma/9327hj5/",
    "https://www.apartments.com/31-worthington-st-boston-ma/phwn2ps/",
    "https://www.apartments.com/313-chelsea-st-boston-ma-unit-ph501/5sbc90m/",
    "https://www.apartments.com/317-saint-paul-st-brookline-ma-unit-2/dj3v4ph/",
    "https://www.apartments.com/32-boylston-st-boston-ma/vphk3rf/",
    "https://www.apartments.com/32-linden-st-brookline-ma-unit-1/7e015yz/",
    "https://www.apartments.com/32-linden-st-brookline-ma-unit-3/pc32kkr/",
    "https://www.apartments.com/32-newcastle-rd-boston-ma-unit-32/2597d1b/",
    "https://www.apartments.com/32-newcastle-rd-boston-ma-unit-32/6m469yr/",
    "https://www.apartments.com/32-orkney-rd-boston-ma-unit-1/v5ss5bd/",
    "https://www.apartments.com/32-waters-ave-everett-ma-unit-1/4cgznek/",
    "https://www.apartments.com/3215-washington-st-boston-ma-unit-1/t3l3tnc/",
    "https://www.apartments.com/3238-washington-st-boston-ma-unit-3/4ple87k/",
    "https://www.apartments.com/328-saint-paul-st-brookline-ma-unit-4/b40ntvc/",
    "https://www.apartments.com/33-gray-st-boston-ma-unit-1/jpxgsx6/",
    "https://www.apartments.com/33-merriam-st-somerville-ma-unit-3/t5g412c/",
    "https://www.apartments.com/33-merriam-st-somerville-ma/7mthxdx/",
    "https://www.apartments.com/33-pratt-st-boston-ma/sz7cbm4/",
    "https://www.apartments.com/33-shannon-st-boston-ma-unit-2/91c0tf5/",
    "https://www.apartments.com/33-westgate-rd-boston-college-ma-unit-1/y1xxncr/",
    "https://www.apartments.com/331-faneuil-st-boston-ma-unit-1/s7s1574/",
    "https://www.apartments.com/331-harvard-st-cambridge-ma-unit-1/dz27whl/",
    "https://www.apartments.com/332-washington-st-boston-ma-unit-1/g3zq2vw/",
    "https://www.apartments.com/334-centre-st-boston-ma-unit-1/j5rer94/",
    "https://www.apartments.com/338-warren-st-boston-ma-unit-3/7z8d8zy/",
    "https://www.apartments.com/34-ash-st-cambridge-ma/1gg2ds7/",
    "https://www.apartments.com/34-cottage-st-chelsea-ma-unit-3/8ydkz60/",
    "https://www.apartments.com/34-matchett-st-boston-ma-unit-2/jvptz96/",
    "https://www.apartments.com/34-newton-st-boston-ma-unit-2/0b2fq50/",
    "https://www.apartments.com/34-ward-st-boston-ma-unit-3/3sc7dye/",
    "https://www.apartments.com/349-meridian-st-boston-ma-unit-1/gys9g0y/",
    "https://www.apartments.com/35-champney-st-boston-ma-unit-2/xw92hgm/",
    "https://www.apartments.com/35-danny-rd-boston-ma-unit-35-danny-rd/61snl2s/",
    "https://www.apartments.com/35-faneuil-st-boston-ma-unit-1/qxgkbyy/",
    "https://www.apartments.com/35-faneuil-st-boston-ma-unit-2/n0jypfp/",
    "https://www.apartments.com/35-harold-st-boston-ma-unit-1/ghzbs3y/",
    "https://www.apartments.com/35-harold-st-boston-ma-unit-3/mhzc1fh/",
    "https://www.apartments.com/35-manning-st-boston-ma-unit-1/68h931r/",
    "https://www.apartments.com/35-park-st-brookline-ma-unit-2/2eg9089/",
    "https://www.apartments.com/35-westgate-rd-boston-college-ma-unit-2/kgfdkz9/",
    "https://www.apartments.com/35-wigglesworth-st-boston-ma/e7hjctn/",
    "https://www.apartments.com/359-newbury-st-boston-ma-unit-610/bfcrmkb/",
    "https://www.apartments.com/36-boston-st-boston-ma-unit-2/43q8nyl/",
    "https://www.apartments.com/36-joy-st-boston-ma-unit-c/s6095f6/",
    "https://www.apartments.com/36-lexington-ave-boston-ma-unit-1a/rdksgz3/",
    "https://www.apartments.com/36-manet-rd-chestnut-hill-ma-unit-2/tbd1c88/",
    "https://www.apartments.com/36-new-st-boston-ma-unit-702/9sb20n6/",
    "https://www.apartments.com/36-newton-st-boston-ma-unit-2/v76yr1e/",
    "https://www.apartments.com/365-centre-st-boston-ma-unit-2/7str04z/",
    "https://www.apartments.com/36r-otis-st-somerville-ma-unit-2/573rvhq/",
    "https://www.apartments.com/37-danny-rd-boston-ma-unit-37-danny-rd-2nd-floor/nvxpebn/",
    "https://www.apartments.com/37-jefferson-st-newton-ma-unit-1/vhxt1rd/",
    "https://www.apartments.com/37-temple-pl-boston-ma/10cctw4/",
    "https://www.apartments.com/370-blue-hill-ave-boston-ma-unit-2/zjy91mw/",
    "https://www.apartments.com/38-harvard-ave-brookline-ma-unit-44-6/r18qe73/",
    "https://www.apartments.com/38-jefferson-st-cambridge-ma-unit-3/7225zww/",
    "https://www.apartments.com/38-newton-st-boston-ma/lwt74xd/",
    "https://www.apartments.com/38-s-huntington-ave-boston-ma-unit-2/z39z03y/",
    "https://www.apartments.com/38-stellman-rd-boston-ma/pmwpcst/",
    "https://www.apartments.com/381-dorchester-st-boston-ma/1zl1hd4/",
    "https://www.apartments.com/387-commonwealth-ave-boston-ma/xylfblq/",
    "https://www.apartments.com/39-addington-rd-brookline-ma-unit-3/r3s66z1/",
    "https://www.apartments.com/39-goldsmith-st-boston-ma-unit-2/wrlf0qk/",
    "https://www.apartments.com/395-broadway-cambridge-ma-unit-1a/vkekzjg/",
    "https://www.apartments.com/399-washington-st-brookline-ma-unit-4/1gwz635/",
    "https://www.apartments.com/3a-douglas-st-boston-ma/q5c21ez/",
    "https://www.apartments.com/4-chestnut-pl-boston-ma-unit-2/egjcrxm/",
    "https://www.apartments.com/4-davis-ave-brookline-ma-unit-3c/3kdly9f/",
    "https://www.apartments.com/4-leeds-st-boston-ma/d33rnyk/",
    "https://www.apartments.com/4-leicester-st-boston-ma-unit-2/m26dkgl/",
    "https://www.apartments.com/4-longfellow-pl-boston-ma/hfskem1/",
    "https://www.apartments.com/40-42-lincoln-st-boston-ma-unit-1/henjmh0/",
    "https://www.apartments.com/40-fairmont-st-cambridge-ma-unit-1/95v14m6/",
    "https://www.apartments.com/40-i-st-boston-ma-unit-2/8gs6t10/",
    "https://www.apartments.com/40-mansfield-st-somerville-ma/5t794dp/",
    "https://www.apartments.com/40-newton-st-boston-ma-unit-1/463kxsh/",
    "https://www.apartments.com/40-pearl-st-cambridge-ma-unit-2/bn6e7tb/",
    "https://www.apartments.com/40-prince-st-cambridge-ma/ccjysse/",
    "https://www.apartments.com/40-spring-garden-st-boston-ma-unit-1/32rwzzd/",
    "https://www.apartments.com/40-traveler-st-boston-ma-unit-506/0sy6b41/",
    "https://www.apartments.com/402-e-8th-st-boston-ma/xjczwqq/",
    "https://www.apartments.com/405-huntington-ave-boston-ma-unit-30/k6phzxb/",
    "https://www.apartments.com/41-auburn-st-brookline-ma/ydrrw7t/",
    "https://www.apartments.com/41-greenville-st-somerville-ma-unit-2/7lhstnw/",
    "https://www.apartments.com/41-matchett-st-boston-ma-unit-1/bnhdbmc/",
    "https://www.apartments.com/41-school-st-boston-ma-unit-2/81rdvb2/",
    "https://www.apartments.com/41-w-walnut-park-boston-ma-unit-2/7lkezqz/",
    "https://www.apartments.com/41-walnut-st-dorchester-ma-unit-2/0ve8ws2/",
    "https://www.apartments.com/411-washington-st-boston-ma/gne65kx/",
    "https://www.apartments.com/42-brookledge-st-boston-ma-unit-1/8xrrc52/",
    "https://www.apartments.com/42-crescent-st-somerville-ma/c130pyf/",
    "https://www.apartments.com/42-fresh-pond-ln-cambridge-ma-unit-1/1n95w16/",
    "https://www.apartments.com/42-fresh-pond-ln-cambridge-ma-unit-1/gddcexy/",
    "https://www.apartments.com/42-north-beacon-st-boston-ma-unit-305/xvj7fpq/",
    "https://www.apartments.com/42-raymond-st-boston-ma-unit-1/mvexqdj/",
    "https://www.apartments.com/429-quincy-shore-dr-quincy-ma-unit-2/kf60w29/",
    "https://www.apartments.com/429-quincy-shore-dr-quincy-ma-unit-2/qc0etsw/",
    "https://www.apartments.com/43-mount-pleasant-ave-boston-ma-unit-3/6dknxls/",
    "https://www.apartments.com/43-parkton-rd-boston-ma-unit-2/gz6pbjz/",
    "https://www.apartments.com/430-e-8th-st-boston-ma/brnbnm9/",
    "https://www.apartments.com/433-park-dr-boston-ma-unit-2/j1w8kc4/",
    "https://www.apartments.com/435-walnut-ave-boston-ma-unit-007/ctvvxjf/",
    "https://www.apartments.com/435-walnut-ave-boston-ma-unit-4/jzzr6l6/",
    "https://www.apartments.com/436-revere-st-winthrop-ma/ppq0fzs/",
    "https://www.apartments.com/439-walnut-ave-boston-ma/3rx08jd/",
    "https://www.apartments.com/439-washington-st-brookline-ma-unit-6/v4eshnf/",
    "https://www.apartments.com/44-beacon-st-chelsea-ma-unit-4/y3y241t/",
    "https://www.apartments.com/44-donnybrook-rd-boston-ma-unit-2/mwf4lhh/",
    "https://www.apartments.com/44-glencoe-st-boston-ma-unit-1/xvf6flm/",
    "https://www.apartments.com/44-michigan-ave-somerville-ma-unit-1/7n9ylfy/",
    "https://www.apartments.com/443-washington-st-boston-ma/jbk5rd7/",
    "https://www.apartments.com/447-e-8th-st-boston-ma/r7sfw33/",
    "https://www.apartments.com/447-w-4th-st-boston-ma-unit-2/xr6ck1n/",
    "https://www.apartments.com/45-garden-st-boston-ma-unit-b/y3v402v/",
    "https://www.apartments.com/45-henshaw-st-boston-ma-unit-2/ex3h2bm/",
    "https://www.apartments.com/45-henshaw-st-boston-ma-unit-2/zvvqh1y/",
    "https://www.apartments.com/45-hunnewell-ave-boston-ma-unit-1/6l6wswt/",
    "https://www.apartments.com/45-nottinghill-rd-boston-ma-unit-2/k98nhnb/",
    "https://www.apartments.com/455-harvard-st-brookline-ma-unit-204a/m7p0lck/",
    "https://www.apartments.com/455-harvard-st-brookline-ma-unit-300/sf7rf96/",
    "https://www.apartments.com/46-hobson-st-boston-ma-unit-1/6dz4vpt/",
    "https://www.apartments.com/46-hobson-st-boston-ma-unit-2/6e0vj3s/",
    "https://www.apartments.com/46-lancaster-ter-brookline-ma-unit-212n/sq4ekb6/",
    "https://www.apartments.com/46-lexington-st-boston-ma/jwfpn17/",
    "https://www.apartments.com/46-newcastle-rd-boston-ma-unit-2/ztphjcz/",
    "https://www.apartments.com/47-hunt-st-quincy-ma-unit-3/79bxr5x/",
    "https://www.apartments.com/47-iffley-rd-boston-ma-unit-3/5mwbmsn/",
    "https://www.apartments.com/47-iffley-rd-boston-ma-unit-3/emx2mzn/",
    "https://www.apartments.com/47-matchett-st-boston-ma-unit-1/s1cees5/",
    "https://www.apartments.com/47-orkney-rd-boston-ma-unit-2/rgl5620/",
    "https://www.apartments.com/476-columbus-ave-boston-ma-unit-13/qy0se2w/",
    "https://www.apartments.com/476-e-3rd-st-boston-ma-unit-2/9jh41q6/",
    "https://www.apartments.com/48-beacon-park-watertown-ma-unit-2/nb3c02q/",
    "https://www.apartments.com/489-e-broadway-boston-ma-unit-4/d7y551k/",
    "https://www.apartments.com/49-bowdoin-st-boston-ma-unit-3/cvltyhg/",
    "https://www.apartments.com/49-dana-ave-boston-ma-unit-2/7hdkr1z/",
    "https://www.apartments.com/5-auckland-st-boston-ma-unit-1/cn8bs3d/",
    "https://www.apartments.com/5-dalrymple-st-boston-ma-unit-3/1cedv77/",
    "https://www.apartments.com/5-delaware-pl-boston-ma-unit-3/ycx4rgs/",
    "https://www.apartments.com/5-eastern-ave-dedham-ma-unit-26/ycjsgyv/",
    "https://www.apartments.com/5-shepard-st-boston-ma-unit-1/jf3m9y5/",
    "https://www.apartments.com/5-sparhawk-st-boston-ma-unit-1/rhqysf1/",
    "https://www.apartments.com/5-sparhawk-st-boston-ma-unit-2/8fcj9k1/",
    "https://www.apartments.com/5-stockton-st-boston-ma-unit-1/t26fbw8/",
    "https://www.apartments.com/5-thane-st-boston-ma-unit-1/zbds5wy/",
    "https://www.apartments.com/50-aspinwall-rd-boston-ma-unit-3/l898qsg/",
    "https://www.apartments.com/50-burnett-st-boston-ma-unit-3/v40tqwg/",
    "https://www.apartments.com/50-king-st-boston-ma/sgf6e25/",
    "https://www.apartments.com/50-leo-m-birmingham-pky-boston-ma-unit-509/9nn0lx5/",
    "https://www.apartments.com/50-lewis-st-boston-ma/mmp1yzj/",
    "https://www.apartments.com/50-undine-rd-boston-ma-unit-1/j7tzes7/",
    "https://www.apartments.com/508-heath-st-brookline-ma-unit-1za/8dzrtc0/",
    "https://www.apartments.com/514-talbot-ave-boston-ma-unit-3/v2drlve/",
    "https://www.apartments.com/523-e-3rd-st-boston-ma-unit-1/yh532rv/",
    "https://www.apartments.com/525-e-3rd-st-boston-ma-unit-r2/tyqprm8/",
    "https://www.apartments.com/525-western-ave-boston-ma/hzc36n0/",
    "https://www.apartments.com/53-chestnut-hill-ave-boston-ma-unit-3/j5g0eg5/",
    "https://www.apartments.com/53-w-7th-st-boston-ma-unit-2/2h2d809/",
    "https://www.apartments.com/53-w-7th-st-boston-ma-unit-2/m9zy4kk/",
    "https://www.apartments.com/54-athol-st-boston-ma-unit-1/0srtx33/",
    "https://www.apartments.com/54-blue-hill-ave-boston-ma-unit-2/xv89fkp/",
    "https://www.apartments.com/54-bowdoin-st-boston-ma-unit-3/09d1fb1/",
    "https://www.apartments.com/54-bowdoin-st-boston-ma-unit-3/fwmgt9v/",
    "https://www.apartments.com/54-townsend-st-boston-ma/bf2hnbb/",
    "https://www.apartments.com/540-atlantic-ave-boston-ma/j1fme57/",
    "https://www.apartments.com/548-washington-st-boston-ma/2kz652c/",
    "https://www.apartments.com/55-colborne-rd-boston-ma-unit-4/9452sc7/",
    "https://www.apartments.com/55-linden-st-boston-ma/7d38rbw/",
    "https://www.apartments.com/55-whitten-st-boston-ma-unit-1/0bvxlq3/",
    "https://www.apartments.com/550-washington-st-boston-ma/qltg4vx/",
    "https://www.apartments.com/56-mansfield-st-boston-ma/82p1e73/",
    "https://www.apartments.com/56-torrey-st-boston-ma-unit-3/4ley2xl/",
    "https://www.apartments.com/57-aspinwall-ave-brookline-ma-unit-2/978xv54/",
    "https://www.apartments.com/57-capitol-st-watertown-ma-unit-1/dkjhc4j/",
    "https://www.apartments.com/57-capitol-st-watertown-ma-unit-2/lm53ysg/",
    "https://www.apartments.com/57-portsmouth-st-boston-ma-unit-1/y0k279v/",
    "https://www.apartments.com/58-aspinwall-ave-brookline-ma-unit-2/8l646r0/",
    "https://www.apartments.com/58-atkins-st-boston-ma-unit-1/ljpb7xe/",
    "https://www.apartments.com/58-brock-st-boston-ma-unit-3/1vlzxn5/",
    "https://www.apartments.com/58-brock-st-boston-ma-unit-3/wtpwpyj/",
    "https://www.apartments.com/58-leo-m-birmingham-pky-boston-ma-unit-4/jllybt5/",
    "https://www.apartments.com/59-brainerd-rd-boston-ma-unit-604/6kty7dt/",
    "https://www.apartments.com/59-faraday-st-boston-ma-unit-1/7v4bzry/",
    "https://www.apartments.com/595-albany-st-boston-ma/4jq8xyl/",
    "https://www.apartments.com/595-albany-st-boston-ma/wvstxqk/",
    "https://www.apartments.com/5a-sparhawk-st-boston-ma-unit-2/hhc81m2/",
    "https://www.apartments.com/6-ashmont-ct-boston-ma-unit-3/demvm4l/",
    "https://www.apartments.com/6-ashmont-ct-boston-ma-unit-3/kxvmvn8/",
    "https://www.apartments.com/6-bearse-ave-boston-ma-unit-3/2eq9ny8/",
    "https://www.apartments.com/6-bearse-ave-boston-ma-unit-3/8recsj2/",
    "https://www.apartments.com/6-camelot-ct-boston-ma/v662wze/",
    "https://www.apartments.com/6-claridge-ter-boston-ma-unit-1/qh1pe6x/",
    "https://www.apartments.com/6-hingham-st-cambridge-ma/8sm6ql1/",
    "https://www.apartments.com/6-imbaro-rd-boston-ma/6f9rwls/",
    "https://www.apartments.com/6-louisburg-sq-boston-ma-unit-ph/lsrnx5g/",
    "https://www.apartments.com/6-oakview-ter-boston-ma-unit-1/d8e96jk/",
    "https://www.apartments.com/6-shepard-st-boston-ma-unit-1/w15g80k/",
    "https://www.apartments.com/6-wabeno-st-boston-ma-unit-3/gplrx2w/",
    "https://www.apartments.com/60-rogers-st-cambridge-ma/39x65nd/",
    "https://www.apartments.com/60-woodlawn-st-boston-ma-unit-3/x40ypvm/",
    "https://www.apartments.com/609-albany-st-boston-ma/2l77xh8/",
    "https://www.apartments.com/61-algonquin-rd-chestnut-hill-ma-unit-61/26bq8v9/",
    "https://www.apartments.com/61-crescent-ave-boston-ma/4jmxfwj/",
    "https://www.apartments.com/61-dorchester-ave-boston-ma-unit-300/1bcl4f6/",
    "https://www.apartments.com/61-middle-st-boston-ma-unit-3/lvg2e9g/",
    "https://www.apartments.com/619-e-3rd-st-boston-ma-unit-3/sbkj4m6/",
    "https://www.apartments.com/62-ainsworth-st-boston-ma-unit-2/rwd6kv2/",
    "https://www.apartments.com/620-huntington-ave-boston-ma/m1j286h/",
    "https://www.apartments.com/626-e-4th-st-boston-ma/dxhhyhj/",
    "https://www.apartments.com/626-e-4th-st-boston-ma/w1z6w2k/",
    "https://www.apartments.com/63-clifton-st-boston-ma-unit-3/rjpf3h0/",
    "https://www.apartments.com/63-farragut-rd-boston-ma-unit-3/bx7rj7c/",
    "https://www.apartments.com/63-farragut-rd-boston-ma-unit-3/ek3gm0p/",
    "https://www.apartments.com/63-farragut-rd-boston-ma-unit-3/vms9mzd/",
    "https://www.apartments.com/63-leyden-st-boston-ma-unit-1/6rtfwjv/",
    "https://www.apartments.com/63-melcher-st-boston-ma-unit-308/xgt84mq/",
    "https://www.apartments.com/631-washington-st-boston-ma/9xy0hx7/",
    "https://www.apartments.com/64-langley-rd-boston-ma/zt1cjhx/",
    "https://www.apartments.com/64-litchfield-st-boston-ma-unit-1/9ptcnx5/",
    "https://www.apartments.com/64-tremont-st-boston-ma-unit-3/6fvpcxv/",
    "https://www.apartments.com/65-bigelow-st-boston-ma-unit-2/f00vglr/",
    "https://www.apartments.com/65-cameron-st-brookline-ma-unit-2e/bdr0pyb/",
    "https://www.apartments.com/65-chiswick-rd-boston-ma-unit-14/9xfef25/",
    "https://www.apartments.com/65-merriam-st-somerville-ma-unit-1/7tf343y/",
    "https://www.apartments.com/658-washington-st-boston-ma/6rbkvpv/",
    "https://www.apartments.com/66-middle-st-boston-ma-unit-2/5f2j6qm/",
    "https://www.apartments.com/66-middle-st-boston-ma-unit-2/g9p1fky/",
    "https://www.apartments.com/66-middle-st-boston-ma-unit-2/v8qngxg/",
    "https://www.apartments.com/68-brayton-rd-boston-ma-unit-2/61ep4cv/",
    "https://www.apartments.com/68-day-st-boston-ma-unit-3/hn9pf60/",
    "https://www.apartments.com/68-staniford-st-boston-ma-unit-914/2y5em79/",
    "https://www.apartments.com/686-parker-st-boston-ma-unit-1/wm589jk/",
    "https://www.apartments.com/69-appleton-st-boston-ma-unit-1/jydcgl7/",
    "https://www.apartments.com/691-massachusetts-ave-boston-ma-unit-401/g7fre3y/",
    "https://www.apartments.com/692-columbia-rd-boston-ma-unit-2/dwcvrdj/",
    "https://www.apartments.com/7-bostonia-ave-brighton-ma-unit-apt-b/lnq97mf/",
    "https://www.apartments.com/7-leeds-st-boston-ma-unit-1/gr6v5ew/",
    "https://www.apartments.com/7-story-st-cambridge-ma-unit-3/sdsj547/",
    "https://www.apartments.com/7-strathmore-rd-brookline-ma-unit-3/1eg6pn6/",
    "https://www.apartments.com/7-university-rd-brookline-ma-unit-3/7v878zy/",
    "https://www.apartments.com/7-wendell-st-cambridge-ma-unit-3/3jvxg4d/",
    "https://www.apartments.com/70-leo-m-birmingham-pkwy-boston-ma-unit-505/514ct1n/",
    "https://www.apartments.com/70-leo-m-birmingham-pky-boston-ma-unit-3/jqgyv55/",
    "https://www.apartments.com/70-leo-m-birmingham-pky-boston-ma-unit-416/rf9tng2/",
    "https://www.apartments.com/70-morse-st-watertown-ma-unit-2/nm8ck9q/",
    "https://www.apartments.com/701-e-2nd-st-boston-ma-unit-2/2kdj4sb/",
    "https://www.apartments.com/71-walnut-park-boston-ma-unit-3/6tzhq6t/",
    "https://www.apartments.com/71-walnut-park-boston-ma-unit-3/ern1eqn/",
    "https://www.apartments.com/71-walnut-park-boston-ma/5np2wmp/",
    "https://www.apartments.com/72-dehon-st-revere-ma-unit-b1/6f49qbr/",
    "https://www.apartments.com/726-e-2nd-st-boston-ma-unit-2-no-fee/9h18y65/",
    "https://www.apartments.com/74-ashford-st-boston-ma/0ztv462/",
    "https://www.apartments.com/74-romsey-st-boston-ma-unit-3/8wpes80/",
    "https://www.apartments.com/74-stanton-st-boston-ma-unit-2/612sejt/",
    "https://www.apartments.com/75-83-83-cambridge-pkwy-cambridge-ma-unit-e1008/fsxthfv/",
    "https://www.apartments.com/75-83-83-cambridge-pkwy-cambridge-ma-unit-w1102/k4rl1yc/",
    "https://www.apartments.com/75-gardena-st-boston-ma/8y9srj2/",
    "https://www.apartments.com/75-morris-st-boston-ma-unit-1/b3j1ts9/",
    "https://www.apartments.com/75-morris-st-boston-ma/zyp519x/",
    "https://www.apartments.com/76-ashford-st-boston-ma/k9wnt4c/",
    "https://www.apartments.com/76-colborne-rd-boston-ma-unit-1/vpeczje/",
    "https://www.apartments.com/768-e-6th-st-boston-ma-unit-2/090jmq0/",
    "https://www.apartments.com/768-e-6th-st-boston-ma-unit-2/qqxxjxx/",
    "https://www.apartments.com/77-ballou-ave-boston-ma-unit-3/ywhnmgr/",
    "https://www.apartments.com/77-falcon-st-boston-ma-unit-2/sc3qjr4/",
    "https://www.apartments.com/77-saint-andrew-rd-boston-ma-unit-2/pn0g1rt/",
    "https://www.apartments.com/77-st-andrew-rd-boston-ma-unit-2/w2blblk/",
    "https://www.apartments.com/775-harrison-ave-boston-ma-unit-305/6sd1mer/",
    "https://www.apartments.com/78-brooks-st-boston-ma-unit-1/6ss827v/",
    "https://www.apartments.com/782-morton-st-boston-ma-unit-3/2dexn0c/",
    "https://www.apartments.com/783-tremont-st-boston-ma/480b57j/",
    "https://www.apartments.com/79-ballou-ave-boston-ma-unit-3/w6eptth/",
    "https://www.apartments.com/79-falcon-st-boston-ma-unit-2/j3sfke6/",
    "https://www.apartments.com/79-falcon-st-boston-ma-unit-2/qpynhcx/",
    "https://www.apartments.com/79-westland-ave-boston-ma/y45ebft/",
    "https://www.apartments.com/8-auckland-st-boston-ma-unit-1/qjr928w/",
    "https://www.apartments.com/8-bentham-rd-boston-ma-unit-2/2dbfd39/",
    "https://www.apartments.com/8-eulita-ter-boston-ma-unit-2/3m4m7gd/",
    "https://www.apartments.com/8-glenmont-rd-boston-ma-unit-1/07jekf2/",
    "https://www.apartments.com/8-hardwick-ter-boston-ma/2jn8ps9/",
    "https://www.apartments.com/8-imrie-rd-boston-ma/cdxsbld/",
    "https://www.apartments.com/8-patten-st-watertown-ma/d5eps2j/",
    "https://www.apartments.com/80-wallingford-rd-boston-ma-unit-1/1ls67m4/",
    "https://www.apartments.com/804-centre-st-boston-ma-unit-2/zt3kyby/",
    "https://www.apartments.com/804-centre-st-boston-ma-unit-5/ymr9hwt/",
    "https://www.apartments.com/81-e-berkeley-st-boston-ma/tx01l6b/",
    "https://www.apartments.com/81-empire-st-boston-ma/wr9ttcj/",
    "https://www.apartments.com/83-bolton-st-boston-ma-unit-1/n37fwzp/",
    "https://www.apartments.com/83-brighton-ave-boston-ma-unit-1/b67tmeb/",
    "https://www.apartments.com/83-essex-st-boston-ma/l1sjjjg/",
    "https://www.apartments.com/83-leyden-st-boston-ma-unit-1/v6zwxjd/",
    "https://www.apartments.com/83-leyden-st-boston-ma-unit-1/zeqychy/",
    "https://www.apartments.com/83-main-st-boston-ma-unit-1/edmn8mq/",
    "https://www.apartments.com/84-commonwealth-ave-boston-ma-unit-4/kqdh31b/",
    "https://www.apartments.com/84-commonwealth-ave-boston-ma-unit-4/y9enm9v/",
    "https://www.apartments.com/848-massachusetts-ave-cambridge-ma-unit-3/9n12wp7/",
    "https://www.apartments.com/85-brainerd-rd-boston-ma-unit-310/8qdv370/",
    "https://www.apartments.com/85-charles-st-boston-ma/k27vfdb/",
    "https://www.apartments.com/85-commonwealth-ave-boston-ma-unit-4/whtt7sl/",
    "https://www.apartments.com/85-fairbanks-st-boston-ma/r57fbl3/",
    "https://www.apartments.com/857-e-1st-st-boston-ma-unit-2/gl46klz/",
    "https://www.apartments.com/857-e-1st-st-boston-ma-unit-2/jrnzjf5/",
    "https://www.apartments.com/861-e-1st-st-boston-ma-unit-3/9n43qm5/",
    "https://www.apartments.com/861-e-1st-st-boston-ma-unit-3/py0ytes/",
    "https://www.apartments.com/862-e-5th-st-boston-ma-unit-1/e2qwgbq/",
    "https://www.apartments.com/87-cottage-st-boston-ma-unit-2/qwe7ewx/",
    "https://www.apartments.com/87-garden-st-cambridge-ma-unit/xwqk70p/",
    "https://www.apartments.com/87-sheridan-st-boston-ma/rr1sls3/",
    "https://www.apartments.com/875-beacon-st-boston-ma-unit-1/85q38g1/",
    "https://www.apartments.com/881-harrison-ave-boston-ma-unit-4/mjy005l/",
    "https://www.apartments.com/89-claybourne-st-boston-ma-unit-3/1jdlg77/",
    "https://www.apartments.com/89-cottage-st-boston-ma/mcn4swj/",
    "https://www.apartments.com/89-princeton-st-boston-ma-unit-3/sxkqkp6/",
    "https://www.apartments.com/9-bostonia-ave-brighton-ma-unit-1/kemk9g8/",
    "https://www.apartments.com/9-conrad-st-boston-ma-unit-2/eylfldp/",
    "https://www.apartments.com/9-glencoe-st-boston-ma-unit-303/3vp6jcd/",
    "https://www.apartments.com/9-shannon-st-boston-ma/nvll1lp/",
    "https://www.apartments.com/9-worcester-st-cambridge-ma-unit-2/ej24ktp/",
    "https://www.apartments.com/90-claybourne-st-boston-ma-unit-3/02grd30/",
    "https://www.apartments.com/90-corbet-st-boston-ma-unit-3/v7p2kbe/",
    "https://www.apartments.com/91-devon-st-boston-ma-unit-3/ee55cjp/",
    "https://www.apartments.com/92-l-st-boston-ma/451l4jj/",
    "https://www.apartments.com/92-st-botolph-st-boston-ma-unit-5/dddq2fl/",
    "https://www.apartments.com/93-george-st-boston-ma-unit-1/m3dmrdk/",
    "https://www.apartments.com/93-glen-st-somerville-ma-unit-3/2s9e8w9/",
    "https://www.apartments.com/93-surrey-st-boston-ma-unit-nm/9q6vds4/",
    "https://www.apartments.com/93-undine-rd-boston-ma-unit-2/85m88v1/",
    "https://www.apartments.com/95-prince-st-boston-ma-unit-7/82986n3/",
    "https://www.apartments.com/959-dorchester-ave-dorchester-ma/gmkd3kz/",
    "https://www.apartments.com/96-e-cottage-st-boston-ma-unit-1/tzrhkjc/",
    "https://www.apartments.com/96-houston-ave-milton-ma/mrdft7k/",
    "https://www.apartments.com/97-hudson-st-boston-ma-unit-e/1bf7916/",
    "https://www.apartments.com/98-toxteth-st-brookline-ma-unit-3/3wj1pzf/",
    "https://www.apartments.com/99-hudson-st-boston-ma-unit-e/v5r8vdf/",
    "https://www.apartments.com/99-marion-st-brookline-ma-unit-3/jbky0e5/",
    "https://www.apartments.com/993-shirley-st-winthrop-ma/hpl76f1/",
    "https://www.apartments.com/christopher-columbus-plaza-boston-ma/y0bp9wv/",
    "https://www.apartments.com/commonwealth-manor-allston-ma/7erq7xz/",
    "https://www.apartments.com/ten-essex-cambridge-ma/9mm23c7/",
    "https://www.apartments.com/the-laneway-roxbury-crossing-ma/cqn66ff/"
]

# Create an empty list to store extracted text
extracted_text_list = []

# Define the path to the Desktop directory
desktop_path = os.path.expanduser("~/Desktop")

# ... (previous imports and setup)

# Loop through the URLs
for url in urls:
    try:
        print(f"Processing URL: {url}")

        # Open the URL
        driver.get(url)
        
        # Wait for elements to load
        driver.implicitly_wait(10)
        
        # Wait for the parent element to be present
        wait = WebDriverWait(driver, 10)
        parent_element = wait.until(EC.presence_of_element_located((By.ID, "descriptionSection")))

        # Extract the text from the specified sections
        listings = parent_element.find_elements(By.XPATH, ".//section[contains(@class, 'mortar-wrapper')]")

        for idx, listing in enumerate(listings, start=1):
            unit_info_element = listing.find_elements(By.XPATH, ".//h2[contains(@class, 'sectionTitle')]")
            if unit_info_element:
                unit_info = unit_info_element[0].text
                unit_description_element = listing.find_elements(By.XPATH, ".//h2[contains(@class, 'sectionTitle') and contains(text(), 'Unit Description')]/following-sibling::p[1]")
                unit_description = unit_description_element[0].text if unit_description_element else "Info not found"
                lease_info_element = listing.find_elements(By.XPATH, ".//h2[contains(@class, 'sectionTitle') and contains(text(), 'Lease Information')]/following-sibling::p[1]")
                lease_info = lease_info_element[0].text if lease_info_element else "Info not found"
                features_element = listing.find_elements(By.XPATH, ".//h2[contains(@class, 'sectionTitle') and contains(text(), 'Features')]/following-sibling::ul[1]")
                features = features_element[0].text if features_element else "Info not found"
                
                # Create a unique filename based on the URL and listing index
                filename = f"{url.split('/')[-2]}_{idx}"  # Include listing index in filename
                output_csv_filename = os.path.join(desktop_path, f"{filename}_details.csv")  # Save to the desktop directory
                
                # Save extracted data along with URL to a CSV file with the unique filename
                with open(output_csv_filename, "w", newline="", encoding="utf-8") as csvfile:
                    csv_writer = csv.writer(csvfile)
                    csv_writer.writerow(["URL", "Unit Info", "Unit Description", "Lease Information", "Features"])
                    csv_writer.writerow([url, unit_info, unit_description, lease_info, features])
                
                print(f"CSV file saved for URL {url}, listing {idx}")
            else:
                print(f"URL {url}, listing {idx}: Info not found")
    except Exception as e:
        print(f"An error occurred for URL {url}: {e}")

# Close the web driver instances
driver.quit()
