import requests
from bs4 import BeautifulSoup
import csv
import os


# Create a list of example URLs
urls = [
    "https://www.apartments.com/1-blackstone-st-cambridge-ma-unit-1b/p9rpc5t/",
    "https://www.apartments.com/1-briarfield-rd-milton-ma-unit-a/3fpg6pg/",
    "https://www.apartments.com/1-devonshire-st-boston-ma/1xps3w4/",
    "https://www.apartments.com/1-fayette-st-cambridge-ma-unit-2/nez13zp/",
    "https://www.apartments.com/1-johnny-ct-boston-ma-unit-1/wny464h/",
    "https://www.apartments.com/10-bearse-ave-boston-ma-unit-3/db3zsvh/",
    "https://www.apartments.com/10-bennington-st-newton-ma-unit-1/vcpqzfe/",
    "https://www.apartments.com/10-charlesgate-e-boston-ma-unit-201/d384s4k/",
    "https://www.apartments.com/10-clipper-ship-ln-boston-ma/vyy93sg/",
    "https://www.apartments.com/10-cufflin-st-boston-ma-unit-2/1vzfy64/",
    "https://www.apartments.com/10-cufflin-st-boston-ma/fmyyb3v/",
    "https://www.apartments.com/10-glenmont-rd-boston-ma-unit-2/1t09mp7/",
    "https://www.apartments.com/10-oliva-rd-boston-ma-unit-2/jnj6646/",
    "https://www.apartments.com/10-pratt-st-boston-ma-unit-2/mbvkh1j/",
    "https://www.apartments.com/10-saco-st-boston-ma-unit-4/3feqbtd/",
    "https://www.apartments.com/10-wave-ave-boston-ma/1perkf5/",
    "https://www.apartments.com/10-westland-ave-boston-ma-unit-u-40/mx8zqdk/",
    "https://www.apartments.com/10-winter-st-cambridge-ma-unit-1/gdnx4hw/",
    "https://www.apartments.com/100-1st-ave-boston-ma/x059wln/",
    "https://www.apartments.com/100-pearl-st-chelsea-ma-unit-13/c4wvx1d/",
    "https://www.apartments.com/101-broad-st-boston-ma-unit-6b/smvv8c4/",
    "https://www.apartments.com/101-chelsea-st-boston-ma/cjrgl8f/",
    "https://www.apartments.com/1028-commonwealth-ave-boston-ma/14w0f64/",
    "https://www.apartments.com/1029-tremont-st-boston-ma-unit-3/r187251/",
    "https://www.apartments.com/105-brookline-st-chestnut-hill-ma-unit-314/yqtrgtt/",
    "https://www.apartments.com/105-forest-hills-st-boston-ma/4l4qngj/",
    "https://www.apartments.com/106-forest-hills-st-boston-ma-unit-103/cb1mq9g/",
    "https://www.apartments.com/106-forest-hills-st-boston-ma-unit-3/1x3c636/",
    "https://www.apartments.com/106-forest-hills-st-boston-ma/07mljd2/",
    "https://www.apartments.com/106-forest-hills-st-boston-ma/z82409y/",
    "https://www.apartments.com/106-hyde-park-ave-boston-ma/jtz4jy7/",
    "https://www.apartments.com/106-myrtle-st-boston-ma/pgeh4qr/",
    "https://www.apartments.com/107-buttonwood-st-boston-ma-unit-3/rwdwvm3/",
    "https://www.apartments.com/107-chandler-st-boston-ma-unit-g/w7qm4el/",
    "https://www.apartments.com/108-appleton-st-boston-ma-unit-a/hf3tb02/",
    "https://www.apartments.com/108-buttonwood-st-boston-ma-unit-3/3k25e6d/",
    "https://www.apartments.com/108-buttonwood-st-boston-ma-unit-3/fwbdw8r/",
    "https://www.apartments.com/11-breck-ave-boston-ma-unit-2aa/2blzw58/",
    "https://www.apartments.com/11-crest-hill-rd-somerville-ma-unit-2/zcgf56z/",
    "https://www.apartments.com/11-holly-ave-cambridge-ma-unit-2/c233lse/",
    "https://www.apartments.com/11-joseph-st-boston-ma-unit-1/5vvx2xq/",
    "https://www.apartments.com/11-new-st-boston-ma-unit-22/8qrw131/",
    "https://www.apartments.com/11-new-st-boston-ma/f7nnzwv/",
    "https://www.apartments.com/11-peterborough-st-boston-ma-unit-1/1ve1nt7/",
    "https://www.apartments.com/11-sparhawk-st-boston-ma-unit-1/2xfm6s9/",
    "https://www.apartments.com/11-stickney-ave-somerville-ma-unit-1/00gh4n1/",
    "https://www.apartments.com/1110-massachusetts-ave-cambridge-ma-unit-4/91fefb5/",
    "https://www.apartments.com/1148-washington-st-boston-ma/31mpmkd/",
    "https://www.apartments.com/115-kilsyth-rd-boston-ma-unit-1/hffgsr0/",
    "https://www.apartments.com/115-union-st-boston-ma-unit-3/ey3kkln/",
    "https://www.apartments.com/116-gladstone-st-boston-ma-unit-2/nyyb4wq/",
    "https://www.apartments.com/116-riverway-boston-ma-unit-16/ffdk0xr/",
    "https://www.apartments.com/116-willow-st-cambridge-ma-unit-4/w2c3bzj/",
    "https://www.apartments.com/1165-commonwealth-ave-boston-ma/1yw8jv5/",
    "https://www.apartments.com/117-harrishof-st-boston-ma-unit-2/j06wq96/",
    "https://www.apartments.com/118-governor-winthrop-rd-somerville-ma-unit-1/r2nvd82/",
    "https://www.apartments.com/118-lake-st-boston-ma/vt8lfjf/",
    "https://www.apartments.com/119-george-st-boston-ma-unit-2/vnp16yf/",
    "https://www.apartments.com/12-eulita-ter-boston-ma-unit-2/ecsth3p/",
    "https://www.apartments.com/12-lopez-ave-cambridge-ma-unit-2/130cns5/",
    "https://www.apartments.com/12-lopez-ave-cambridge-ma-unit-2/97x3fr6/",
    "https://www.apartments.com/12-pratt-st-boston-ma-unit-1/vts783g/",
    "https://www.apartments.com/12-wensley-st-boston-ma-unit-3n/gtrmmzw/",
    "https://www.apartments.com/12-winter-st-boston-ma/r3lh363/",
    "https://www.apartments.com/120-gladstone-st-boston-ma-unit-2/zx0x93x/",
    "https://www.apartments.com/121-bigelow-st-boston-ma-unit-2/njenrbm/",
    "https://www.apartments.com/122-bennett-st-boston-ma-unit-1a/clbbsrg/",
    "https://www.apartments.com/122-cottage-st-boston-ma-unit-4f/eemqqwp/",
    "https://www.apartments.com/123-border-st-boston-ma-unit-5/hqxf731/",
    "https://www.apartments.com/123-boston-st-boston-ma-unit-1/mxp6pbk/",
    "https://www.apartments.com/123-boston-st-boston-ma-unit-2/mt7ez4k/",
    "https://www.apartments.com/123-sewall-ave-brookline-ma-unit-1a/nsqls8m/",
    "https://www.apartments.com/123-sutherland-rd-boston-ma-unit-g/3rj443d/",
    "https://www.apartments.com/123-trenton-st-boston-ma-unit-3/94kyqx6/",
    "https://www.apartments.com/124-kenrick-st-boston-ma-unit-3/nb7r8ym/",
    "https://www.apartments.com/126a-babcock-st-brookline-ma-unit-26/n4rj5dp/",
    "https://www.apartments.com/127-blue-hill-ave-milton-ma-unit-1/0msq4k0/",
    "https://www.apartments.com/127-eliot-st-chestnut-hill-ma-unit-1/dc4k8hk/",
    "https://www.apartments.com/127-nonantum-st-boston-ma-unit-2/fdfp9wv/",
    "https://www.apartments.com/128-everett-st-boston-ma-unit-2/2zknzpb/",
    "https://www.apartments.com/129-sutherland-rd-boston-ma/7k2glwx/",
    "https://www.apartments.com/1298-commonwealth-ave-boston-ma-unit-6/3s0nvmd/",
    "https://www.apartments.com/13-glenley-ter-boston-ma-unit-2/xltwrcn/",
    "https://www.apartments.com/13-pleasant-st-cambridge-ma-unit-1/zfswvlz/",
    "https://www.apartments.com/13-pleasant-st-cambridge-ma-unit-2/8x2mjd3/",
    "https://www.apartments.com/13-sachem-st-boston-ma-unit-1/0mg5w21/",
    "https://www.apartments.com/13-sparhawk-st-boston-ma/jjzz7k4/",
    "https://www.apartments.com/13-sparhawk-st-boston-ma/z8lnd0z/",
    "https://www.apartments.com/1306-columbia-rd-boston-ma-unit-3e/4zqqmtk/",
    "https://www.apartments.com/132-lake-shore-rd-boston-ma-unit-1/x2wp1bn/",
    "https://www.apartments.com/1340-boylston-st-boston-ma-unit-1a/ps8pm3t/",
    "https://www.apartments.com/136-parsons-st-boston-ma/4krls0l/",
    "https://www.apartments.com/137-fayerweather-st-cambridge-ma-unit-1/1w8cel6/",
    "https://www.apartments.com/139-fresh-pond-pkwy-cambridge-ma/srwd9m4/",
    "https://www.apartments.com/14-batchelder-st-boston-ma-unit-2/3ffc59g/",
    "https://www.apartments.com/14-bothwell-rd-boston-ma-unit-1/zwsk5gy/",
    "https://www.apartments.com/14-glenmont-rd-boston-ma-unit-1/mybv8gj/",
    "https://www.apartments.com/14-linnaean-st-cambridge-ma/q9htg4x/",
    "https://www.apartments.com/14-marion-st-brookline-ma/h7kbng1/",
    "https://www.apartments.com/14-parmenter-st-boston-ma-unit-403/y92emwr/",
    "https://www.apartments.com/14-portsmouth-st-boston-ma-unit-c/4rszhcj/",
    "https://www.apartments.com/14-townsend-st-boston-ma-unit-4/c1g6m2f/",
    "https://www.apartments.com/14-townsend-st-boston-ma-unit-4/y6660qv/",
    "https://www.apartments.com/14-w-broadway-boston-ma-unit-201half-fee/c4vwzje/",
    "https://www.apartments.com/140-kenrick-st-boston-ma-unit-2/zgyc5zx/",
    "https://www.apartments.com/141-chelsea-st-boston-ma-unit-3/vpt14tg/",
    "https://www.apartments.com/1410-columbia-rd-boston-ma/z14qn0w/",
    "https://www.apartments.com/1416-commonwealth-ave-boston-ma-unit-402/zgz40gy/",
    "https://www.apartments.com/1424-columbia-rd-boston-ma/gykk8cw/",
    "https://www.apartments.com/1426-columbia-rd-boston-ma/l2gz1tf/",
    "https://www.apartments.com/1430-tremont-st-boston-ma-unit-b4n/czsv8se/",
    "https://www.apartments.com/1463-beacon-st-brookline-ma-unit-4/sflb7d5/",
    "https://www.apartments.com/148-allston-st-cambridge-ma-unit-1/gzr22vz/",
    "https://www.apartments.com/149-g-st-boston-ma/3981dzg/",
    "https://www.apartments.com/15-germania-st-boston-ma-unit-3/1m2vd77/",
    "https://www.apartments.com/15-greycliff-rd-boston-ma-unit-2/0f4gjz2/",
    "https://www.apartments.com/15-kelley-ct-boston-ma-unit-02n/qz9e5ry/",
    "https://www.apartments.com/15-romsey-st-boston-ma-unit-3/jnhlcq4/",
    "https://www.apartments.com/15-sparhawk-st-boston-ma-unit-1/cl9lp8g/",
    "https://www.apartments.com/15-sparhawk-st-boston-ma/k2wpb59/",
    "https://www.apartments.com/15-ward-st-boston-ma-unit-4/7mq28sz/",
    "https://www.apartments.com/15-westland-ave-boston-ma-unit-39/z1wspty/",
    "https://www.apartments.com/150-south-st-boston-ma-unit-3/qr0h0ey/",
    "https://www.apartments.com/151-g-st-boston-ma/nr7sl8q/",
    "https://www.apartments.com/151-park-dr-boston-ma/vjfs8ye/",
    "https://www.apartments.com/1522-vfw-pky-boston-ma-unit-202/5bpk59p/",
    "https://www.apartments.com/1525-cambridge-st-cambridge-ma-unit-2/rrd7lk0/",
    "https://www.apartments.com/153-cherry-st-cambridge-ma-unit-1/xvfbk1p/",
    "https://www.apartments.com/153-foster-st-boston-ma-unit-3/hvnd352/",
    "https://www.apartments.com/154-bigelow-st-boston-ma/wv3xzsj/",
    "https://www.apartments.com/155-strathmore-rd-boston-ma/e78jxrm/",
    "https://www.apartments.com/157-bowdoin-st-boston-ma-unit-1/vpc3w1f/",
    "https://www.apartments.com/158-boston-st-boston-ma-unit-3/d3tmr0l/",
    "https://www.apartments.com/1583-beacon-st-brookline-ma-unit-3/qrsw5lw/",
    "https://www.apartments.com/16-crescent-circuit-s-cres-boston-ma-unit-2/cp8r1wf/",
    "https://www.apartments.com/16-donnybrook-rd-boston-ma-unit-2/58e8b2n/",
    "https://www.apartments.com/16-elko-st-boston-ma-unit-1/l0d5l7g/",
    "https://www.apartments.com/16-garrison-rd-brookline-ma-unit-7/0qg74v3/",
    "https://www.apartments.com/16-irving-st-boston-ma-unit-8/f5403jt/",
    "https://www.apartments.com/16-oakview-ter-boston-ma-unit-3/swp2mg4/",
    "https://www.apartments.com/16-parmenter-st-boston-ma-unit-403/wrtxq6k/",
    "https://www.apartments.com/16-s-crescent-circuit-boston-ma-unit-2/3lke18d/",
    "https://www.apartments.com/160-bigelow-st-boston-ma/52h7qsm/",
    "https://www.apartments.com/160-e-berkeley-st-boston-ma-unit-305/jmq2g47/",
    "https://www.apartments.com/160-e-berkeley-st-boston-ma/879z0l3/",
    "https://www.apartments.com/162-lincoln-st-boston-ma-unit-1610/jjwd5v4/",
    "https://www.apartments.com/162-wachusett-st-jamaica-plain-ma-unit-1/s91dzx7/",
    "https://www.apartments.com/164-bigelow-st-boston-ma-unit-1/qm6cm6w/",
    "https://www.apartments.com/1661-washington-st-boston-ma/y6hn2er/",
    "https://www.apartments.com/167-thorndike-st-cambridge-ma-unit-1/hmzkrn0/",
    "https://www.apartments.com/168-bigelow-st-boston-ma/4t5m91h/",
    "https://www.apartments.com/169-monsignor-obrien-hwy-cambridge-ma-unit-601/tttlrsc/",
    "https://www.apartments.com/169-thorndike-st-cambridge-ma-unit-2/kwdlkd8/",
    "https://www.apartments.com/169-tremont-st-newton-ma-unit-1/w6pcwel/",
    "https://www.apartments.com/17-falkland-st-boston-ma-unit-2/39hltxd/",
    "https://www.apartments.com/17-grove-st-boston-ma-unit-4/0bhb923/",
    "https://www.apartments.com/17-middle-st-boston-ma-unit-3/jvecb85/",
    "https://www.apartments.com/17-nottinghill-rd-boston-ma-unit-1/bx4mzy8/",
    "https://www.apartments.com/17-nottinghill-rd-boston-ma-unit-2n/rn8df02/",
    "https://www.apartments.com/17-winter-st-boston-ma/8mz1zg1/",
    "https://www.apartments.com/171-173-i-st-boston-ma-unit-2/khyq6f9/",
    "https://www.apartments.com/171-cambridge-st-boston-ma-unit-2/0l9men3/",
    "https://www.apartments.com/171-south-st-boston-ma-unit-5a/4qf333h/",
    "https://www.apartments.com/171-thorndike-st-cambridge-ma-unit-1/tzqbx68/",
    "https://www.apartments.com/1719-commonwealth-ave-boston-ma-unit-3/w7y9f4l/",
    "https://www.apartments.com/172-green-st-boston-ma/6fs4rhv/",
    "https://www.apartments.com/173-border-st-boston-ma/hcvzzr0/",
    "https://www.apartments.com/175-high-st-brookline-ma-unit-1/rkd6qg0/",
    "https://www.apartments.com/177-bennington-st-boston-ma-unit-4/hm6bc43/",
    "https://www.apartments.com/1789-commonwealth-ave-boston-ma-unit-1/25sd3nb/",
    "https://www.apartments.com/1789-commonwealth-ave-boston-ma-unit-1/clxcwdd/",
    "https://www.apartments.com/1789-commonwealth-ave-boston-ma/0wvyxw2/",
    "https://www.apartments.com/1789-commonwealth-ave-boston-ma/v7fe52e/",
    "https://www.apartments.com/1789-commonwealth-avenue-boston-ma/1xmbc74/",
    "https://www.apartments.com/18-bradbury-st-boston-ma-unit-1/hkj7cd0/",
    "https://www.apartments.com/18-gibson-st-boston-ma-unit-2/djd12eh/",
    "https://www.apartments.com/18-glenmont-rd-boston-ma-unit-1/3bvpm7d/",
    "https://www.apartments.com/18-glenville-ave-boston-ma-unit-1/c98l68e/",
    "https://www.apartments.com/18-grove-boston-ma/zctnw8w/",
    "https://www.apartments.com/18-grove-st-boston-ma-unit-1/jj4mkh5/",
    "https://www.apartments.com/18-highgate-st-boston-ma/ybn0r9s/",
    "https://www.apartments.com/18-holton-st-boston-ma/vk32zeg/",
    "https://www.apartments.com/18-hunnewell-ave-boston-ma-unit-2/2szbh9c/",
    "https://www.apartments.com/18-lopez-st-cambridge-ma-unit-3/c915jtf/",
    "https://www.apartments.com/18-parmenter-st-boston-ma-unit-3/9mkpvv5/",
    "https://www.apartments.com/18-parmenter-st-boston-ma-unit-403/q5bmqfz/",
    "https://www.apartments.com/18-parmenter-st-boston-ma-unit-403/r25n972/",
    "https://www.apartments.com/18-parmenter-st-boston-ma-unit-403/vm7znze/",
    "https://www.apartments.com/181-harvard-st-brookline-ma-unit-3a/ce15b9d/",
    "https://www.apartments.com/181-harvard-st-brookline-ma/cbq8m9g/",
    "https://www.apartments.com/181-m-st-boston-ma-unit-2/nemkclp/",
    "https://www.apartments.com/185-green-st-boston-ma-unit-3/jd9q5v5/",
    "https://www.apartments.com/1860-commonwealth-ave-boston-ma-unit-3/t77c9d8/",
    "https://www.apartments.com/187-harvard-st-brookline-ma-unit-3/jvvpq24/",
    "https://www.apartments.com/189-chestnut-hill-ave-boston-ma-unit-19/wrfp0dh/",
    "https://www.apartments.com/19-archdale-rd-boston-ma-unit-1/383f65f/",
    "https://www.apartments.com/19-dorset-st-boston-ma-unit-3/g48cg1z/",
    "https://www.apartments.com/19-edward-t-sullivan-rd-cambridge-ma-unit-3/9ffc2z7/",
    "https://www.apartments.com/19-fairbanks-st-brookline-ma-unit-3/rpjdc33/",
    "https://www.apartments.com/19-litchfield-st-boston-ma-unit-2/nv12ljp/",
    "https://www.apartments.com/19-nottinghill-rd-boston-ma-unit-nm/yhdffgr/",
    "https://www.apartments.com/19-parker-hill-ave-boston-ma-unit-2/jwffm87/",
    "https://www.apartments.com/19-saint-lukes-rd-boston-ma-unit-1/q0ce0by/",
    "https://www.apartments.com/19-worthington-st-boston-ma-unit-2/gnk4hgy/",
    "https://www.apartments.com/190-green-st-boston-ma/wzw2n1k/",
    "https://www.apartments.com/191-bunker-hill-st-boston-ma-unit-apt-306/f32p8jv/",
    "https://www.apartments.com/191-porter-st-boston-ma-unit-5/n2rwh2q/",
    "https://www.apartments.com/194-emerson-st-boston-ma-unit-3/c2nhzvf/",
    "https://www.apartments.com/196-tremont-st-newton-ma-unit-3/et29r7n/",
    "https://www.apartments.com/198-brookline-ave-boston-ma/21crb7c/",
    "https://www.apartments.com/2-bow-st-cambridge-ma-unit-2/g971pgx/",
    "https://www.apartments.com/2-rossmore-rd-boston-ma-unit-2/t97qkm8/",
    "https://www.apartments.com/2-rossmore-rd-boston-ma/qt7e5gy/",
    "https://www.apartments.com/2-thane-st-boston-ma-unit-2/2614bgb/",
    "https://www.apartments.com/2-wellington-st-boston-ma-unit-6/knfdde8/",
    "https://www.apartments.com/20-brooks-st-boston-ma-unit-1/bd6yn5c/",
    "https://www.apartments.com/20-dawes-st-boston-ma/91fk6b7/",
    "https://www.apartments.com/20-howell-st-boston-ma-unit-2/6h87zhs/",
    "https://www.apartments.com/20-penniman-rd-boston-ma-unit-208/tvzsmk8/",
    "https://www.apartments.com/20-south-st-boston-ma/nqtd99q/",
    "https://www.apartments.com/20-westgate-rd-boston-ma-unit-1/071dz70/",
    "https://www.apartments.com/20-westland-ave-boston-ma-unit-39/j3w2z76/",
    "https://www.apartments.com/200-commonwealth-ave-chestnut-hill-ma-unit-1n/v9ctxxf/",
    "https://www.apartments.com/201-longwood-ave-brookline-ma/06vyb20/",
    "https://www.apartments.com/202-stuart-st-boston-ma/8mgc212/",
    "https://www.apartments.com/204-cambridge-st-boston-ma/xe3wc2m/",
    "https://www.apartments.com/207-aspinwall-ave-brookline-ma/gnr40cz/",
    "https://www.apartments.com/209-green-st-boston-ma-unit-206/43frfdl/",
    "https://www.apartments.com/21-nottinghill-rd-boston-ma/xk67n8p/",
    "https://www.apartments.com/21-sparhawk-st-boston-ma-unit-2/kyb0dmb/",
    "https://www.apartments.com/21-weitz-st-boston-ma-unit-2/rsd1xq1/",
    "https://www.apartments.com/211-green-st-boston-ma-unit-212/c21rm5g/",
    "https://www.apartments.com/211-green-st-boston-ma-unit-505/rdrcqv3/",
    "https://www.apartments.com/211-green-st-jamaica-plain-ma/rkj3l20/",
    "https://www.apartments.com/212-hemenway-st-boston-ma-unit-4/cvlklge/",
    "https://www.apartments.com/215-saint-paul-st-brookline-ma-unit-3/31j7w2f/",
    "https://www.apartments.com/216-newbury-st-boston-ma-unit-4/z53045w/",
    "https://www.apartments.com/217-south-st-boston-ma-unit-7/9qs9vb5/",
    "https://www.apartments.com/217-w-2nd-st-boston-ma/mlet6zh/",
    "https://www.apartments.com/219-w-2nd-st-boston-ma-unit-221/02zp5w2/",
    "https://www.apartments.com/22-concord-ave-somerville-ma-unit-2b/9dwfgv5/",
    "https://www.apartments.com/22-hayden-st-boston-ma/9bzhk47/",
    "https://www.apartments.com/22-laurel-st-watertown-ma-unit-2/e7fr02p/",
    "https://www.apartments.com/22-winslow-rd-brookline-ma-unit-1/evk057p/",
    "https://www.apartments.com/22-woodworth-st-boston-ma/r2995h2/",
    "https://www.apartments.com/220-old-colony-ave-boston-ma/ref1vm2/",
    "https://www.apartments.com/220-tremont-st-newton-ma-unit-1/ffjvxyv/",
    "https://www.apartments.com/221-w-2nd-st-boston-ma-unit-2/7fkcv2x/",
    "https://www.apartments.com/221-w-2nd-st-boston-ma/l8wd1lg/",
    "https://www.apartments.com/221-w-2nd-st-boston-ma/n61lxzp/",
    "https://www.apartments.com/23-elmore-st-boston-ma-unit-3/574qlvn/",
    "https://www.apartments.com/23-lambert-st-cambridge-ma-unit-2/73d7f6z/",
    "https://www.apartments.com/23-marcella-st-boston-ma-unit-2/4wplskh/",
    "https://www.apartments.com/23-morrow-rd-boston-ma-unit-2/xn8p42q/",
    "https://www.apartments.com/23-ward-st-boston-ma-unit-2/c143cce/",
    "https://www.apartments.com/230-brookline-st-cambridge-ma-unit-1/cv55bhg/",
    "https://www.apartments.com/230-everett-st-boston-ma-unit-8/5zr71yn/",
    "https://www.apartments.com/230-everett-st-boston-ma-unit-8/nzwmx1n/",
    "https://www.apartments.com/233-boylston-st-brookline-ma-unit-3/l2wvl7d/",
    "https://www.apartments.com/238-hemenway-st-boston-ma-unit-3/hsb03n0/",
    "https://www.apartments.com/24-annafran-st-boston-ma-unit-3/gv9k0zy/",
    "https://www.apartments.com/24-bentley-st-boston-ma-unit-1/qt1qc3x/",
    "https://www.apartments.com/24-breed-st-boston-ma-unit-1/yhq64xr/",
    "https://www.apartments.com/24-tower-st-boston-ma-unit-2/11mssn5/",
    "https://www.apartments.com/240-hanover-st-boston-ma-unit-510/716et2z/",
    "https://www.apartments.com/241-tremont-st-newton-ma-unit-1/bembx68/",
    "https://www.apartments.com/247-d-st-boston-ma/53gtntm/",
    "https://www.apartments.com/25-bennett-st-boston-ma/t4yqk3c/",
    "https://www.apartments.com/25-dwight-st-boston-ma-unit-4/x5nc3cp/",
    "https://www.apartments.com/25-g-st-boston-ma/9jb5hb7/",
    "https://www.apartments.com/25-greycliff-rd-boston-ma-unit-1/g28n1sw/",
    "https://www.apartments.com/25-henshaw-st-boston-ma-unit-2/dlwwjxk/",
    "https://www.apartments.com/25-lothrop-st-boston-ma-unit-2/jrr59m7/",
    "https://www.apartments.com/25-worthington-st-boston-ma-unit-1/yfnb0cs/",
    "https://www.apartments.com/250-newbury-st-boston-ma/29yy359/",
    "https://www.apartments.com/251-cambridge-st-boston-ma-unit-3/23h82x9/",
    "https://www.apartments.com/251-cambridge-st-boston-ma-unit-3/272m88b/"
]  

extracted_text_list = []

for url in urls:
    try:
        print(f"Processing URL: {url}")

        # Send an HTTP GET request and get the HTML content
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for non-2xx status codes
        html_content = response.text
        
        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(html_content, "html.parser")
        
        # Find the element containing the text you want to extract
        description_element = soup.find("div", id="descriptionSection")
        
        if description_element:
            # Extract the text from the element
            about_property_text = description_element.get_text(strip=True)
            
            # Append the extracted text to the list
            extracted_text_list.append((url, about_property_text))
        
    except Exception as e:
        print(f"An error occurred for URL {url}: {e}")

# Define the path to the Desktop directory
desktop_path = os.path.expanduser("~/Desktop")

# Create a CSV file with the extracted text
output_csv_filename = os.path.join(desktop_path, "extracted_text.csv")
with open(output_csv_filename, "w", newline="", encoding="utf-8") as csvfile:
    csv_writer = csv.writer(csvfile)
    csv_writer.writerow(["URL", "About Property"])
    csv_writer.writerows(extracted_text_list)

print("CSV file saved with extracted text.")